# Generated by Django 4.2.1 on 2023-05-31 11:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('question_text', models.CharField(max_length=200)),
                ('course_id', models.IntegerField(default=0)),
                ('course_module_id', models.IntegerField(default=0)),
                ('tags', models.CharField(max_length=500)),
                ('penalty', models.FloatField(default=1.0)),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('changed_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date changed')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=500)),
                ('answer_format', models.IntegerField(default=0)),
                ('fraction', models.FloatField(default=1.0)),
                ('feedback', models.CharField(default=0, max_length=50)),
                ('feedback_format', models.IntegerField(default=0)),
                ('question', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lmsbaikal.question')),
            ],
        ),
    ]
